### ISSUE TITLE
mvcUnique support pushdata length more than 2**8

### ISSUE THREAD

**Issue by chainfrog** [metasv/metacontract-script-decoder#3]
code in this block has restrict the data length < 2**8
https://github.com/mvc-labs/metacontract-script-decoder/blob/master/mvc_unique.go#L27

```
if !(pkScript[scriptLen-totalDataLen-1-1-1] == OP_RETURN &&
		pkScript[scriptLen-totalDataLen-1-1] == 0x4c &&
		pkScript[scriptLen-totalDataLen-1] == byte(totalDataLen)) {
		return false
	}
```

`0x4c` is op_pushdata1, there has 0x1-0x4b(data length: 1 ~ 0x4b), op_pushdata2(data length: 2\**8 ~ 2\**16), op_pushdata4(data length: 2\**16~ 2\**32)

fixed 256 bytes may be too small for some unique contracts

**Comment by heosum** [comment]
some issue editor correction

0x4c is op_pushdata1, there has 0x1-0x4b(data length: 1 ~ 0x4b), op_pushdata2(data length: 28 ~ 216), op_pushdata4(data length: 216~ 232)

=>

`0x4c` is op_pushdata1, there has 0x1-0x4b(data length: 1 ~ 0x4b), op_pushdata2(data length: 2\**8 ~ 2\**16), op_pushdata4(data length: 2\**16~ 2\**32)

**Comment by KaKeimei** [comment]
fixed in https://github.com/metasv/metacontract-script-decoder/pull/4

**Comment by KaKeimei** [comment]
fixed in https://github.com/metasv/metacontract-script-decoder/pull/5
